{
 "title": "Demo App Dashboard (Canary)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Success rate (upstream)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(irate(envoy_cluster_upstream_rq_xx{app=\"demo-app-canary\",envoy_response_code_class!~\"5\"}[1m])) /\nsum(irate(envoy_cluster_upstream_rq_xx{app=\"demo-app-canary\"}[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success rate (downstream)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{app=\"demo-app-canary\",envoy_response_code_class!~\"5\", envoy_http_conn_manager_prefix=\"ingress\"}[1m])) /\n          sum(irate(envoy_http_downstream_rq_xx{app=\"demo-app-canary\",envoy_http_conn_manager_prefix=\"ingress\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests (upstream)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{app=\"demo-app-canary\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 2xx HTTP requests (downstream)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{app=\"demo-app-canary\", envoy_http_conn_manager_prefix=\"ingress\", envoy_response_code_class=\"2\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total 5xx HTTP requests (downstream)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{app=\"demo-app-canary\", envoy_http_conn_manager_prefix=\"ingress\", envoy_response_code_class=\"5\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP requests (downstream)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{app=\"demo-app-canary\", envoy_http_conn_manager_prefix=\"ingress\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}