---
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: gateway-route-paths
  namespace: app
  labels:
    gateway: ingress-gw
spec:
  httpRoute:
    match:
      prefix: "/canary"
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: my-canary-vsvc
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  namespace: app
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: demo-app-canary
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  gateways:
  - istio-gw
  hosts:
  - "*"
  http:
  - name: primary
    route:
    - destination:
        host: demo-app-canary
        subset: stable
      weight: 100
    - destination:
        host: demo-app-canary
        subset: canary
      weight: 0


---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: canary-destrule
spec:
  host: demo-app-canary
  subsets:
  - name: canary  
    labels:     
      app: demo-app-canary
  - name: stable  
    labels:  
      app: demo-app-canary
